products = [
    {
        "nome": "Fragment x Travis Scott – Jordan 1 Retro Low OG SP",
        "categoria": "scarpe",
        "taglia_us": "12.5",
        "taglia_eu": "47.5",
        "valore_attuale_eur": 1500,
        "link_immagine_fronte": None,
        "link_immagine_retro": None,
        "link_stockx": None,
    },
    {
        "nome": "Ishod Wair x Magnus Walker – Nike SB Dunk High Pro",
        "categoria": "scarpe",
        "taglia_us": "10.5",
        "taglia_eu": "44.5",
        "valore_attuale_eur": 400,
        "link_immagine_fronte": None,
        "link_immagine_retro": None,
        "link_stockx": None,
    },
    {
        "nome": "Zen Master – Jordan 4 Retro",
        "categoria": "scarpe",
        "taglia_us": "12",
        "taglia_eu": "46",
        "valore_attuale_eur": 250,
        "link_immagine_fronte": None,
        "link_immagine_retro": None,
        "link_stockx": None,
    },
    {
        "nome": "AMBUSH Deep Royal – Nike Dunk High",
        "categoria": "scarpe",
        "taglia_us": "8.5",
        "taglia_eu": "42",
        "valore_attuale_eur": 200,
        "link_immagine_fronte": None,
        "link_immagine_retro": None,
        "link_stockx": None,
    },
    {
        "nome": "Travis Scott Cactus Jack Saturn Gold – Nike Air Max 1",
        "categoria": "scarpe",
        "taglia_us": "4.5",
        "taglia_eu": "36.5",
        "valore_attuale_eur": 200,
        "link_immagine_fronte": None,
        "link_immagine_retro": None,
        "link_stockx": None,
    },
    {
        "nome": "White Navy – Jordan 4 SB",
        "categoria": "scarpe",
        "taglia_us": "10",
        "taglia_eu": "44",
        "valore_attuale_eur": 250,
        "link_immagine_fronte": None,
        "link_immagine_retro": None,
        "link_stockx": None,
    },
    {
        "nome": "Supreme – Scatola rossa con bombolette",
        "categoria": "accessori",
        "taglia_us": None,
        "taglia_eu": None,
        "valore_attuale_eur": 80,
        "link_immagine_fronte": None,
        "link_immagine_retro": None,
        "link_stockx": None,
    },
    {
        "nome": "Supreme – Calze viola",
        "categoria": "accessori",
        "taglia_us": "M",
        "taglia_eu": None,
        "valore_attuale_eur": 50,
        "link_immagine_fronte": None,
        "link_immagine_retro": None,
        "link_stockx": None,
    },
    {
        "nome": "Supreme – Guanti",
        "categoria": "accessori",
        "taglia_us": None,
        "taglia_eu": None,
        "valore_attuale_eur": 15,
        "link_immagine_fronte": None,
        "link_immagine_retro": None,
        "link_stockx": None,
    },
    {
        "nome": "Supreme – Adesivi",
        "categoria": "accessori",
        "taglia_us": None,
        "taglia_eu": None,
        "valore_attuale_eur": 15,
        "link_immagine_fronte": None,
        "link_immagine_retro": None,
        "link_stockx": None,
    },
    {
        "nome": "Supreme – Tee bianca con Emilio Pucci",
        "categoria": "maglietta",
        "taglia_us": "S",
        "taglia_eu": None,
        "valore_attuale_eur": 200,
        "link_immagine_fronte": None,
        "link_immagine_retro": None,
        "link_stockx": None,
    },
    {
        "nome": "Thrasher – Tee bianca Rainbow",
        "categoria": "maglietta",
        "taglia_us": "S",
        "taglia_eu": None,
        "valore_attuale_eur": 42,
        "link_immagine_fronte": None,
        "link_immagine_retro": None,
        "link_stockx": None,
    },
    {
        "nome": "Supreme – Tee nera Rainbow",
        "categoria": "maglietta",
        "taglia_us": "S",
        "taglia_eu": None,
        "valore_attuale_eur": 42,
        "link_immagine_fronte": None,
        "link_immagine_retro": None,
        "link_stockx": None,
    },
    {
        "nome": "Stussy Cream – Nike Benassi",
        "categoria": "ciabatte",
        "taglia_us": "7",
        "taglia_eu": "40",
        "valore_attuale_eur": 48,
        "link_immagine_fronte": None,
        "link_immagine_retro": None,
        "link_stockx": None,
    },
]
